local opts = { noremap = true, silent = true }
local vk = vim.keymap
vk.set("", "q", "<Nop>")
vk.set("", "B", "0")
vk.set("", "E", "$")
vk.set("n", "Q", "<nop>")
vk.set("n", "=", "<C-a>")
vk.set("n", "-", "<C-x>")
vk.set("v", "J", ":m '>+1<CR>gv=gv", { silent = true })
vk.set("v", "K", ":m '<-2<CR>gv=gv", { silent = true })
vk.set("", "j", "gj")
vk.set("", "k", "gk")
vk.set("", "<C-d>", "<C-d>zz")
vk.set("", "<C-u>", "<C-u>zz")
vk.set("", "G", "Gzz")
vk.set("", "<C-b>", ":vs<CR>", { silent = true })
vk.set("", "<M-Left>", ":vertical resize +3<CR>", { silent = true })
vk.set("", "<M-Right>", ":vertical resize -3<CR>", { silent = true })
vk.set("", "<M-Up>", ":resize +3<CR>", { silent = true })
vk.set("", "<M-Down>", ":resize -3<CR>", { silent = true })
vk.set("n", "<Esc>", "<cmd>nohlsearch<CR>")
vk.set("n", "n", "nzzzv", opts)
vk.set("n", "<leader>sr", ":%s/<C-r><C-w>//gc<Left><Left><left>", { desc = "Search and replace word under cursor" })
vk.set("n", "<leader>S", ":%s//g<Left><Left>", { desc = "Global substitute" })
vk.set("v", "<leader>S", ":s//g<Left><Left>", { desc = "Substitute in selection" })
vk.set("", "<leader>F", ":FzfLua files<cr>", { desc = "Pick Files" })
vk.set("", "<leader>H", ":FzfLua helptags<cr>", { desc = "help" })
vk.set("", "<leader>gf", ":FzfLua git_files<cr>", { desc = "Pick Files" })
vk.set("", "<leader>ss", ":FzfLua live_grep_native<cr>", { desc = "Live Grep" })
